DROP TABLE IF EXISTS STOCK_TRADE_DETAILS;
CREATE TABLE STOCK_TRADE_DETAILS(
id INT PRIMARY KEY,
Stock_Code	INT,
Stock_name	VARCHAR(20) NOT NULL,
Day_Open	DECIMAL(8,2), 
Day_High	DECIMAL(8,2),  
Day_Low	DECIMAL(8,2),
Traded_Price	DECIMAL(8,2),
Previous_Close	DECIMAL(8,2),
TRADED_DATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP); 